### ISSUE TITLE
parameter values.....

### ISSUE THREAD

**Issue by bigcheesepaul** [unl/LAPSforMac#2]
Hi, not an issue more of a newbie not knowing what parameter values to put :

        Parameter 9: LAPS Account Event
        Parameter 10: LAPS Account Event FVE
        Parameter 11: LAPS Run Event

I know that FVE is the File Vault Enabled, but unsure as to what these parameters values are meant to be populated with.

Thanks in advance
Paul

**Comment by predfern** [comment]
Hi Paul. I just discovered my GitHub emails were being caught by our new spam filter, sorry for the slow response!

Those parameters should reflect the custom Policy triggers. After looking back at the documentation I can see how that is not very clear. I will see if I can improve that. Below is a quick breakdown.

`Parameter 9: LAPS Account Event` 
This should be the custom trigger used in Step 6.
`Trigger: Custom: createLAPSaccount-{AccountShortName}`

`Parameter 10: LAPS Account Event FVE`
This should be the custom trigger used in Step 7.
`Trigger: Custom: createLAPSaccountFVE-{AccountShortName}`

`Parameter 11: LAPS Run Event`
This should be the custom trigger used in Step 8.
`Trigger: Custom: runLAPS`

Let me know if you have any more questions. 

Thanks!
